apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vuxs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-vuxs@sha256:83233f9d0ca98bf5f2048b4cfff111e3c69c90b093d5cbd6319c85d387df8bf2
        name: my-nodejs
        resources: {}
status: {}
